"""create tasks table

Revision ID: 95586137a24d
Revises: 0b1fd62c3f51
Create Date: 2026-10-06 18:27:15.382792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95586137a24d'
down_revision: Union[str, Sequence[str], None] = '0b1fd62c3f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('BACKLOG', 'READY', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='task_status'), server_default='BACKLOG', nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='task_priority'), server_default='MEDIUM', nullable=False),
    sa.Column('type', sa.Enum('FEATURE', 'BUG', 'CHORE', 'TEST', 'DOCS', name='task_type'), server_default='FEATURE', nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tasks_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_tasks_reporter_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('project_id', 'number', name=op.f('uq_tasks_project_id'))
    )
    op.add_column('projects', sa.Column('next_task_number', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'next_task_number')
    op.drop_table('tasks')
    # ### end Alembic commands ###
    # Autogenerate creates the enum types implicitly but never drops them,
    # which makes a later re-upgrade fail with "type already exists".
    sa.Enum(name='task_status').drop(op.get_bind())
    sa.Enum(name='task_priority').drop(op.get_bind())
    sa.Enum(name='task_type').drop(op.get_bind())
