"""create task activities table

Revision ID: d479b9e408cb
Revises: 95586137a24d
Create Date: 2026-10-08 07:42:04.975029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd479b9e408cb'
down_revision: Union[str, Sequence[str], None] = '95586137a24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('USER', 'SYSTEM', 'GITHUB', name='task_activity_source'), nullable=False),
    sa.Column('type', sa.Enum('TASK_CREATED', 'STATUS_CHANGED', 'USER_ASSIGNED', name='task_activity_type'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_task_activities_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_activities_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_activities')),
    sa.UniqueConstraint('seq', name=op.f('uq_task_activities_seq'))
    )
    op.create_index(op.f('ix_task_activities_task_id'), 'task_activities', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_activities_task_id'), table_name='task_activities')
    op.drop_table('task_activities')
    # ### end Alembic commands ###
    # Autogenerate creates the enum types implicitly but never drops them,
    # which makes a later re-upgrade fail with "type already exists".
    sa.Enum(name='task_activity_source').drop(op.get_bind())
    sa.Enum(name='task_activity_type').drop(op.get_bind())
